<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkyscrapersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("skyscrapers")->insert([
            ['id' => '1','name' => 'Chrysler Building','city_id' => '1','height' => '318.9','stories' => '77','finished' => '1930'],
            ['id' => '2','name' => 'Empire State Building','city_id' => '1','height' => '381','stories' => '102','finished' => '1931'],
            ['id' => '3','name' => '875 North Michigan Avenue','city_id' => '2','height' => '343.7','stories' => '100','finished' => '1969'],
            ['id' => '4','name' => 'Aon Center','city_id' => '2','height' => '346.3','stories' => '83','finished' => '1973'],
            ['id' => '5','name' => 'Willis Tower','city_id' => '2','height' => '442.1','stories' => '108','finished' => '1974'],
            ['id' => '6','name' => 'Bank of China Tower','city_id' => '3','height' => '367.4','stories' => '72','finished' => '1990'],
            ['id' => '7','name' => 'Central Plaza','city_id' => '3','height' => '373.9','stories' => '78','finished' => '1992'],
            ['id' => '8','name' => 'CITIC Plaza','city_id' => '4','height' => '390.2','stories' => '80','finished' => '1996'],
            ['id' => '9','name' => 'Shun Hing Square','city_id' => '5','height' => '384','stories' => '69','finished' => '1996'],
            ['id' => '10','name' => '85 Sky Tower','city_id' => '6','height' => '347.5','stories' => '85','finished' => '1997'],
            ['id' => '11','name' => 'Petronas Twin Tower 1','city_id' => '7','height' => '451.9','stories' => '88','finished' => '1998'],
            ['id' => '12','name' => 'Petronas Twin Tower 2','city_id' => '7','height' => '451.9','stories' => '88','finished' => '1998'],
            ['id' => '13','name' => 'The Center','city_id' => '3','height' => '346','stories' => '73','finished' => '1998'],
            ['id' => '14','name' => 'Jin Mao Tower','city_id' => '8','height' => '420.5','stories' => '88','finished' => '1999'],
            ['id' => '15','name' => 'Burj Al Arab','city_id' => '9','height' => '321','stories' => '56','finished' => '1999'],
            ['id' => '16','name' => 'Emirates Tower One','city_id' => '9','height' => '354.6','stories' => '54','finished' => '2000'],
            ['id' => '17','name' => 'Two International Finance Centre','city_id' => '3','height' => '412','stories' => '88','finished' => '2003'],
            ['id' => '18','name' => 'TAIPEI 101','city_id' => '10','height' => '508','stories' => '101','finished' => '2004'],
            ['id' => '19','name' => 'Q1 Tower','city_id' => '11','height' => '322.5','stories' => '78','finished' => '2005'],
            ['id' => '20','name' => 'Shimao International Plaza','city_id' => '8','height' => '333.3','stories' => '60','finished' => '2006'],
            ['id' => '21','name' => 'Nina Tower','city_id' => '3','height' => '320.4','stories' => '80','finished' => '2006'],
            ['id' => '22','name' => 'Rose Rayhaan by Rotana','city_id' => '9','height' => '333','stories' => '71','finished' => '2007'],
            ['id' => '23','name' => 'New York Times Tower','city_id' => '1','height' => '318.8','stories' => '52','finished' => '2007'],
            ['id' => '24','name' => 'Shanghai World Financial Center','city_id' => '8','height' => '492','stories' => '101','finished' => '2008'],
            ['id' => '25','name' => 'Almas Tower','city_id' => '9','height' => '360','stories' => '68','finished' => '2008'],
            ['id' => '26','name' => 'Minsheng Bank Building','city_id' => '12','height' => '331','stories' => '68','finished' => '2008'],
            ['id' => '27','name' => 'Trump International Hotel & Tower','city_id' => '2','height' => '423.2','stories' => '98','finished' => '2009'],
            ['id' => '28','name' => 'Bank of America Tower','city_id' => '1','height' => '365.8','stories' => '55','finished' => '2009'],
            ['id' => '29','name' => 'Burj Khalifa','city_id' => '9','height' => '828','stories' => '163','finished' => '2010'],
            ['id' => '30','name' => 'International Commerce Centre','city_id' => '3','height' => '484','stories' => '108','finished' => '2010'],
            ['id' => '31','name' => 'Zifeng Tower','city_id' => '13','height' => '450','stories' => '66','finished' => '2010'],
            ['id' => '32','name' => 'Guangzhou International Finance Center','city_id' => '4','height' => '438.6','stories' => '103','finished' => '2010'],
            ['id' => '33','name' => 'China World Tower','city_id' => '14','height' => '330','stories' => '74','finished' => '2010'],
            ['id' => '34','name' => 'The Index','city_id' => '9','height' => '326','stories' => '80','finished' => '2010'],
            ['id' => '35','name' => 'Blue Tower','city_id' => '9','height' => '317.6','stories' => '72','finished' => '2010'],
            ['id' => '36','name' => 'KK100','city_id' => '5','height' => '441.8','stories' => '100','finished' => '2011'],
            ['id' => '37','name' => 'Al Hamra Tower','city_id' => '15','height' => '412.6','stories' => '80','finished' => '2011'],
            ['id' => '38','name' => 'The Torch','city_id' => '9','height' => '352','stories' => '86','finished' => '2011'],
            ['id' => '39','name' => 'Tianjin World Financial Center','city_id' => '16','height' => '336.9','stories' => '75','finished' => '2011'],
            ['id' => '40','name' => 'Longxi International Hotel','city_id' => '17','height' => '328','stories' => '72','finished' => '2011'],
            ['id' => '41','name' => 'Wenzhou Trade Center','city_id' => '18','height' => '321.9','stories' => '68','finished' => '2011'],
            ['id' => '42','name' => 'Makkah Royal Clock Tower','city_id' => '19','height' => '601','stories' => '120','finished' => '2012'],
            ['id' => '43','name' => 'Princess Tower','city_id' => '9','height' => '413.4','stories' => '101','finished' => '2012'],
            ['id' => '44','name' => '23 Marina','city_id' => '9','height' => '392.4','stories' => '88','finished' => '2012'],
            ['id' => '45','name' => 'Elite Residence','city_id' => '9','height' => '380.5','stories' => '87','finished' => '2012'],
            ['id' => '46','name' => 'JW Marriott Marquis Hotel Dubai Tower 1','city_id' => '9','height' => '355.4','stories' => '82','finished' => '2012'],
            ['id' => '47','name' => 'The Pinnacle','city_id' => '4','height' => '350.3','stories' => '60','finished' => '2012'],
            ['id' => '48','name' => 'Keangnam Hanoi Landmark Tower','city_id' => '20','height' => '328.6','stories' => '72','finished' => '2012'],
            ['id' => '49','name' => 'JW Marriott Marquis Hotel Dubai Tower 2','city_id' => '9','height' => '355.4','stories' => '82','finished' => '2013'],
            ['id' => '50','name' => 'Mercury City Tower','city_id' => '21','height' => '338.8','stories' => '75','finished' => '2013'],
            ['id' => '51','name' => 'Al Yaqoub Tower','city_id' => '9','height' => '328','stories' => '69','finished' => '2013'],
            ['id' => '52','name' => 'The Landmark','city_id' => '22','height' => '324','stories' => '72','finished' => '2013'],
            ['id' => '53','name' => 'Deji Plaza','city_id' => '13','height' => '324','stories' => '62','finished' => '2013'],
            ['id' => '54','name' => 'One World Trade Center','city_id' => '1','height' => '541.3','stories' => '94','finished' => '2014'],
            ['id' => '55','name' => 'Burj Mohammed Bin Rashid','city_id' => '22','height' => '381.2','stories' => '88','finished' => '2014'],
            ['id' => '56','name' => 'Wuxi International Finance Square','city_id' => '17','height' => '339','stories' => '68','finished' => '2014'],
            ['id' => '57','name' => 'Wuxi Suning Plaza 1','city_id' => '17','height' => '328','stories' => '67','finished' => '2014'],
            ['id' => '58','name' => 'Shanghai Tower','city_id' => '8','height' => '632','stories' => '128','finished' => '2015'],
            ['id' => '59','name' => '432 Park Avenue','city_id' => '1','height' => '425.7','stories' => '85','finished' => '2015'],
            ['id' => '60','name' => 'OKO - Residential Tower','city_id' => '21','height' => '354.2','stories' => '90','finished' => '2015'],
            ['id' => '61','name' => 'Forum 66 Tower 1','city_id' => '23','height' => '350.6','stories' => '68','finished' => '2015'],
            ['id' => '62','name' => 'ADNOC Headquarters','city_id' => '22','height' => '342','stories' => '65','finished' => '2015'],
            ['id' => '63','name' => 'Chongqing World Financial Center','city_id' => '24','height' => '338.9','stories' => '72','finished' => '2015'],
            ['id' => '64','name' => 'Guangzhou CTF Finance Centre','city_id' => '4','height' => '530','stories' => '111','finished' => '2016'],
            ['id' => '65','name' => 'Eton Place Dalian Tower 1','city_id' => '25','height' => '383.2','stories' => '80','finished' => '2016'],
            ['id' => '66','name' => 'Federation Tower','city_id' => '21','height' => '373.7','stories' => '93','finished' => '2016'],
            ['id' => '67','name' => 'Tianjin Modern City Office Tower','city_id' => '16','height' => '338','stories' => '65','finished' => '2016'],
            ['id' => '68','name' => 'Global City Square','city_id' => '4','height' => '318.9','stories' => '67','finished' => '2016'],
            ['id' => '69','name' => 'Fanya International Finance Building North','city_id' => '26','height' => '317.8','stories' => '67','finished' => '2016'],
            ['id' => '70','name' => 'Fanya International Finance Building South','city_id' => '26','height' => '317.8','stories' => '66','finished' => '2016'],
            ['id' => '71','name' => 'Chongqing IFS T1','city_id' => '24','height' => '316.3','stories' => '63','finished' => '2016'],
            ['id' => '72','name' => 'Ping An Finance Center','city_id' => '5','height' => '599.1','stories' => '115','finished' => '2017'],
            ['id' => '73','name' => 'Lotte World Tower','city_id' => '27','height' => '554.5','stories' => '123','finished' => '2017'],
            ['id' => '74','name' => 'Marina 101','city_id' => '9','height' => '425','stories' => '101','finished' => '2017'],
            ['id' => '75','name' => 'The Address Boulevard','city_id' => '9','height' => '370','stories' => '73','finished' => '2017'],
            ['id' => '76','name' => 'Gevora Hotel','city_id' => '9','height' => '356.3','stories' => '75','finished' => '2017'],
            ['id' => '77','name' => 'Wilshire Grand Center','city_id' => '28','height' => '335.3','stories' => '73','finished' => '2017'],
            ['id' => '78','name' => 'Yuexiu Fortune Center Tower 1','city_id' => '12','height' => '330','stories' => '68','finished' => '2017'],
            ['id' => '79','name' => 'Hon Kwok City Center','city_id' => '5','height' => '329.4','stories' => '80','finished' => '2017'],
            ['id' => '80','name' => 'Zhuhai St. Regis Hotel & Office Tower','city_id' => '29','height' => '328.8','stories' => '66','finished' => '2017'],
            ['id' => '81','name' => 'Yantai Shimao No. 1 The Harbour','city_id' => '30','height' => '323','stories' => '59','finished' => '2017'],
            ['id' => '82','name' => 'Guangxi Finance Plaza','city_id' => '31','height' => '321','stories' => '68','finished' => '2017'],
            ['id' => '83','name' => 'Sinar Mas Center 1','city_id' => '8','height' => '320','stories' => '65','finished' => '2017'],
            ['id' => '84','name' => 'Jiuzhou International Tower','city_id' => '31','height' => '318','stories' => '71','finished' => '2017'],
            ['id' => '85','name' => 'CITIC Tower','city_id' => '14','height' => '527.7','stories' => '109','finished' => '2018'],
            ['id' => '86','name' => 'Vincom Landmark 81','city_id' => '32','height' => '461.3','stories' => '81','finished' => '2018'],
            ['id' => '87','name' => 'Changsha IFS Tower T1','city_id' => '33','height' => '452.1','stories' => '94','finished' => '2018'],
            ['id' => '88','name' => 'China Resources Tower','city_id' => '5','height' => '392.5','stories' => '68','finished' => '2018'],
            ['id' => '89','name' => 'Nanning Logan Century 1','city_id' => '31','height' => '381.3','stories' => '82','finished' => '2018'],
            ['id' => '90','name' => 'Hanking Center','city_id' => '5','height' => '358.9','stories' => '65','finished' => '2018'],
            ['id' => '91','name' => 'Four Seasons Place','city_id' => '7','height' => '342.5','stories' => '65','finished' => '2018'],
            ['id' => '92','name' => 'Comcast Technology Center','city_id' => '34','height' => '341.7','stories' => '59','finished' => '2018'],
            ['id' => '93','name' => 'One Shenzhen Bay Tower 7','city_id' => '5','height' => '341.4','stories' => '71','finished' => '2018'],
            ['id' => '94','name' => 'Suning Plaza Tower 1','city_id' => '35','height' => '338','stories' => '75','finished' => '2018'],
            ['id' => '95','name' => 'DAMAC Heights','city_id' => '9','height' => '335.1','stories' => '88','finished' => '2018'],
            ['id' => '96','name' => '3 World Trade Center','city_id' => '1','height' => '328.9','stories' => '69','finished' => '2018'],
            ['id' => '97','name' => 'Baoneng Center','city_id' => '5','height' => '327.3','stories' => '65','finished' => '2018'],
            ['id' => '98','name' => 'Salesforce Tower','city_id' => '36','height' => '326.1','stories' => '61','finished' => '2018'],
            ['id' => '99','name' => 'Wuhan Center Tower','city_id' => '12','height' => '438','stories' => '88','finished' => '2019'],
            ['id' => '100','name' => '30 Hudson Yards','city_id' => '1','height' => '386.6','stories' => '73','finished' => '2019'],
        ]);
    }
}
